// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// MapItemCurrency map item currency
//
// swagger:model MapItemCurrency
type MapItemCurrency map[string]float64

// Validate validates this map item currency
func (m MapItemCurrency) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this map item currency based on context it is used
func (m MapItemCurrency) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
