// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Symbols symbols
//
// swagger:model Symbols
type Symbols struct {

	// success
	Success bool `json:"success,omitempty"`

	// symbols
	Symbols map[string]string `json:"symbols,omitempty"`
}

// Validate validates this symbols
func (m *Symbols) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this symbols based on context it is used
func (m *Symbols) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Symbols) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Symbols) UnmarshalBinary(b []byte) error {
	var res Symbols
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
