// Code generated by go-swagger; DO NOT EDIT.

package rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ervitis/freelancetools/exchangerate/models"
)

// GetLatestReader is a Reader for the GetLatest structure.
type GetLatestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLatestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLatestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetLatestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetLatestTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetLatestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLatestOK creates a GetLatestOK with default headers values
func NewGetLatestOK() *GetLatestOK {
	return &GetLatestOK{}
}

/* GetLatestOK describes a response with status code 200, with default header values.

The foreign exchange reference rates
*/
type GetLatestOK struct {
	Payload *models.Rates
}

func (o *GetLatestOK) Error() string {
	return fmt.Sprintf("[GET /latest][%d] getLatestOK  %+v", 200, o.Payload)
}
func (o *GetLatestOK) GetPayload() *models.Rates {
	return o.Payload
}

func (o *GetLatestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rates)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLatestNotFound creates a GetLatestNotFound with default headers values
func NewGetLatestNotFound() *GetLatestNotFound {
	return &GetLatestNotFound{}
}

/* GetLatestNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type GetLatestNotFound struct {
	Payload *models.Error
}

func (o *GetLatestNotFound) Error() string {
	return fmt.Sprintf("[GET /latest][%d] getLatestNotFound  %+v", 404, o.Payload)
}
func (o *GetLatestNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetLatestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLatestTooManyRequests creates a GetLatestTooManyRequests with default headers values
func NewGetLatestTooManyRequests() *GetLatestTooManyRequests {
	return &GetLatestTooManyRequests{}
}

/* GetLatestTooManyRequests describes a response with status code 429, with default header values.

Rate limit
*/
type GetLatestTooManyRequests struct {
	Payload *models.Error
}

func (o *GetLatestTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /latest][%d] getLatestTooManyRequests  %+v", 429, o.Payload)
}
func (o *GetLatestTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetLatestTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLatestInternalServerError creates a GetLatestInternalServerError with default headers values
func NewGetLatestInternalServerError() *GetLatestInternalServerError {
	return &GetLatestInternalServerError{}
}

/* GetLatestInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetLatestInternalServerError struct {
	Payload *models.Error
}

func (o *GetLatestInternalServerError) Error() string {
	return fmt.Sprintf("[GET /latest][%d] getLatestInternalServerError  %+v", 500, o.Payload)
}
func (o *GetLatestInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetLatestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
